qversion: "3.8"

services:
  document-summarisation-tools:
    container_name: dst-app
    env_file:
      - secret.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    networks:
      - dst-networks
    volumes:
      - /home/develop/repository_document_summary:/app/storage # Mount local directory to container for data persistence
  postgres:
    image: pgvector/pgvector:pg16 # Official image with pgvector pre-installed
    container_name: document_pg_vector
    environment:
      POSTGRES_USER: develop # Set your PostgreSQL username
      POSTGRES_PASSWORD: password  # Set your PostgreSQL password
      POSTGRES_DB: dtskul # Set your default database name
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data # Mount volume for data persistence
    networks:
      - dst-networks
  postgres-sql-demo:
    image: pgvector/pgvector:pg16 # Official image with pgvector pre-installed
    container_name: document_pg_vector_sql_demo
    environment:
      POSTGRES_USER: admin # Set your PostgreSQL username
      POSTGRES_PASSWORD: password # Set your PostgreSQL password
      POSTGRES_DB: mydatabase # Set your default database name
    ports:
      - "54332:5432" # Expose PostgreSQL on port 5432
    volumes:
      - pgdata-sql-demo:/var/lib/postgresql/data # Mount volume for data persistence
    networks:
      - dst-networks

volumes:
  pgdata:
    driver: local
  pgdata-sql-demo:


networks:
  dst-networks: